spring.application.name=SpringSecurity

logging.level.org.springframework.security=DEBUG

//SettingMyOwn-UserName-Password
spring.security.user.name=Kushagra
spring.security.user.password=kush@123savita

